### ISSUE TITLE
New version conflicts with "Undone" Reminder note

### ISSUE THREAD

**Issue by carallo** [maltaisn/another-notes-app#61]
Hi @maltaisn!
Happy new year and thank you for the new update!

I've encountered an issue which I have (kind of casually) been able to fix. After updating to the new version the app was crashing. Thankfully I was able to backup my notes with Titanium and restore them, after downgrading again to the older version.
Long story short, after some tries I've found out I had a note set as "Reminder" which was expired but not marked as "Done". After marking it as done I updated to latest version and it works flawlessly.

Have found this in the log:

> FATAL` EXCEPTION: main
Process: com.maltaisn.notes.sync, PID: 6423
java.lang.IllegalArgumentException: com.maltaisn.notes.sync: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
 at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
 at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
 at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
 at d2.b.c(Unknown Source:23)
 at d2.b.b(Unknown Source:0)
 at com.maltaisn.notes.model.r.e(Unknown Source:69)
 at com.maltaisn.notes.model.r.g(Unknown Source:114)
 at com.maltaisn.notes.model.r$c.h(Unknown Source:11)
 at v3.a.p(Unknown Source:13)
 at l4.v0.run(Unknown Source:129)
 at android.os.Handler.handleCallback(Handler.java:938)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:201)
 at android.os.Looper.loop(Looper.java:288)
 at android.app.ActivityThread.main(ActivityThread.java:7839)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by maltaisn** [comment]
Thanks for the report, I'll fix this ASAP.

**Comment by maltaisn** [comment]
Thanks for the report (and the stacktrace!), it should be fixed now, I'll make a new release.

**Comment by carallo** [comment]
> Thanks for the report (and the stacktrace!), it should be fixed now, I'll make a new release.

Hey, no problem at all, I do what I can (not being a developer). Thanks so much to you for developing and maintaining the app!
