### ISSUE TITLE
Export to Nextcloud fails

### ISSUE THREAD

**Issue by echeoquehaii** [maltaisn/another-notes-app#64]
Hi @maltaisn, sorry for bothering again!
Today I was trying the export function and I noticed I am not able to export to Nextcloud. I have set up the Nextcloud folder in Android's stock file manager to have it accessible from any app. When I try to export to Nextcloud, it goes back to the settings page saying that the backup failed. Still, it creates a 0Kb file in the folder. If I try to export to a normal folder (either internal or SD card) it all goes well.

Here's a log:

```
Data export failed
java.io.FileNotFoundException: Error downloading file: gggg
 at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151)
 at android.content.ContentProviderProxy.openAssetFile(ContentProviderNative.java:705)
 at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1860)
 at android.content.ContentResolver.openOutputStream(ContentResolver.java:1562)
 at com.maltaisn.notes.ui.settings.SettingsFragment.j3(Unknown Source:38)
 at com.maltaisn.notes.ui.settings.SettingsFragment.Y2(Unknown Source:0)
 at v2.f.a(Unknown Source:6)
 at androidx.activity.result.ActivityResultRegistry$1.d(Unknown Source:101)
 at androidx.lifecycle.s$a.a(Unknown Source:14)
 at androidx.lifecycle.s.g(Unknown Source:67)
 at androidx.lifecycle.s.p(Unknown Source:72)
 at androidx.lifecycle.s.l(Unknown Source:19)
 at androidx.lifecycle.s.h(Unknown Source:9)
 at androidx.fragment.app.Fragment.e2(Unknown Source:28)
 at androidx.fragment.app.x.u(Unknown Source:33)
 at androidx.fragment.app.x.m(Unknown Source:73)
 at androidx.fragment.app.y.t(Unknown Source:30)
 at androidx.fragment.app.q.L0(Unknown Source:27)
 at androidx.fragment.app.q.P(Unknown Source:9)
 at androidx.fragment.app.q.O(Unknown Source:11)
 at androidx.fragment.app.Fragment.e2(Unknown Source:42)
 at androidx.fragment.app.x.u(Unknown Source:33)
 at androidx.fragment.app.x.m(Unknown Source:73)
 at androidx.fragment.app.y.t(Unknown Source:30)
 at androidx.fragment.app.q.L0(Unknown Source:27)
 at androidx.fragment.app.q.P(Unknown Source:9)
 at androidx.fragment.app.q.O(Unknown Source:11)
 at androidx.fragment.app.k.q(Unknown Source:4)
 at androidx.fragment.app.h.onStart(Unknown Source:37)
 at e.b.onStart(Unknown Source:0)
 at com.maltaisn.notes.ui.main.MainActivity.onStart(Unknown Source:0)
 at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1455)
 at android.app.Activity.performStart(Activity.java:8075)
 at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3660)
 at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
 at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
 at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
 at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loopOnce(Looper.java:201)
 at android.os.Looper.loop(Looper.java:288)
 at android.app.ActivityThread.main(ActivityThread.java:7839)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by maltaisn** [comment]
Does this still occur? I just tried installed Nextcloud and writing the backup file to it works just fine.

**Comment by echeoquehaii** [comment]
Actually not, it's working fine now! :)

**Comment by maltaisn** [comment]
Great, thanks!
